### ISSUE TITLE
neutron-plugin-api-subordinate-relation-changed returns traceback due to packages missing in repos for train release

### ISSUE THREAD

**Issue by minkimipt** [gabriel-samfira/charm-neutron-api-plugin-ironic#2]
```
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed Traceback (most recent call last):
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/var/lib/juju/agents/unit-neutron-ironic-agent-0/charm/hooks/neutron-plugin-api-subordinate-relation-changed", line 22, in <module>
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     main()
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charms/reactive/__init__.py", line 74, in main
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     bus.dispatch(restricted=restricted_mode)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charms/reactive/bus.py", line 390, in dispatch
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     _invoke(other_handlers)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charms/reactive/bus.py", line 359, in _invoke
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     handler.invoke()
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charms/reactive/bus.py", line 181, in invoke
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     self._action(*args)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/var/lib/juju/agents/unit-neutron-ironic-agent-0/charm/reactive/neutron_ironic_handlers.py", line 43, in install_ironic
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     charm_class.install()
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "lib/charm/openstack/neutron_ironic.py", line 36, in install
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     super().install()
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charms_openstack/charm/core.py", line 655, in install
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     fetch.apt_install(packages, fatal=True)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charmhelpers/fetch/ubuntu.py", line 284, in apt_install
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     _run_apt_command(cmd, fatal)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charmhelpers/fetch/ubuntu.py", line 778, in _run_apt_command
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     retry_message="Couldn't acquire DPKG lock")
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/local/lib/python3.6/dist-packages/charmhelpers/fetch/ubuntu.py", line 756, in _run_with_retries
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     result = subprocess.check_call(cmd, env=env)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed     raise CalledProcessError(retcode, cmd)
2020-10-21 11:50:51 DEBUG neutron-plugin-api-subordinate-relation-changed subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', '--option=Dpkg::Options::=--force-confold', 'install', 'ironic-neutron-agent', 'python3-ironic-neutron-agent']' returned non-zero exit status 100.
```

this can be fixed by installing packages from debs directly:

```
curl -O http://archive.ubuntu.com/ubuntu/pool/universe/n/networking-baremetal/python3-ironic-neutron-agent_1.4.0-2_all.deb
curl -O http://archive.ubuntu.com/ubuntu/pool/universe/n/networking-baremetal/ironic-neutron-agent_1.4.0-2_all.deb
```

**Comment by gabriel-samfira** [comment]
Hi

Those packages are only available in "proposed". Make sure you use:

cloud:bionic-train/proposed

See: https://github.com/gabriel-samfira/charm-ironic-api/blob/master/src/tests/bundles/bionic-train.yaml#L2

**Comment by minkimipt** [comment]
Thank you, got it! Closing.

**Comment by gabriel-samfira** [comment]
One last thing. The charms on the charm store are not yet final. To get the desired result, you will need to use these 2 branches:

https://review.opendev.org/#/c/755977/
https://review.opendev.org/#/c/755978/

Of wait for them to merge and propagate to the store.
